name: CI

on:
  push:
    branches:
      - master  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'  # Adjust Java version as needed

    - name: Run JAR
      run: java -cp ./javac-diagnostics-wrapper.jar io.github.wmdietl.diagnostics.json.sarif.Main ../Main.java
